export DATABASE_URL='postgresql://postgres:localhost:5432/capstone'
# export DATABASE_URL=os.environ["DATABASE_URL"]
# export TEST_DATABASE_URL='postgresql://postgres:localhost:5432/capstone_test'
# export ENV=''
# export FLASK_APP=app
#export AUTH0_DOMAIN='dev-epds.eu.auth0.com'
# export AUTH0_DOMAIN=os.environ["AUTH0_DOMAIN"]
# export ALGORITHMS=['RS256']
# export API_AUDIENCE=os.environ["API_AUDIENCE"]
# export EXITED=os.environ["EXCITED"]
export AUTH0_DOMAIN='dev-epds.eu.auth0.com'
export ALGORITHMS=['RS256']
export API_AUDIENCE='capstone'
export EXITED='true'
